	
		<h2 class="title">Streepjes systeem</h2>
		
		<img src="images/streepjesbord.jpg" alt="Foto" width='30%' />
		<br />
		<em>{ Het streepjesbord }</em>
		<br />
		<br />
		<h2>Waarom dit systeem? </h2>
		
		<p>Eigenlijk om de vrij eenvoudige reden dat er op het krijtbord nogal veel streepjes verdwenen doordat er mensen tegen het bord aanstonden.</p>
		
		<h2>Hoe werkt het?</h2>
		<p>Eigenlijk is het vrij simpel. Wil je een biertje kopen, maar heb je geen geld? Klik boven in het menu op "Strepen". 
		Je krijgt nu een scherm voor je waarin je je naam kunt selecteren en het aantal consumpties van iedere soort. Zet je naam en de aantallen goed
		en druk op de knop "Strepen". Je komt nu in een overzicht waarin je kunt zien hoe groot je schuld is.</p>
		
		<h2>Hoe zit het dan met afbetalen?</h2>
		<p>Heb je nu een keer geld bij je en wil je je streepjes wegwerken? Zoek iemand van het stambestuur 
		bij hun kun je je geld kwijt. Zij zullen dit ook verwerken in dit systeem.</p>
		
		<h2>Foutje?</h2>
		<p>Denk je dat er iets niet goed gegaan is in het systeem, of heb je zelf iets fout ingevoerd? Stuur dan een mailtje naar 
		stambestuur@diekantankys.nl. Vermeld in dat mailtje ook de tijd van het invoeren.</p>
		
		

